### PR TITLE
Scraping API UI and db Changes

### PR DESCRIPTION
**Pull request by Divy0409**
## Using this Pull Request Template
1. In the Description of Changes section below, please fill out the details requested
2. Create the pull request
3. Check the boxes in the Type of Change section that apply to your changes
4. Check the boxes in the Checklist Before Review section that apply
5. Assign at least two reviewers to review your pull request by clicking the settings icon next to Reviewers

## Description of Changes
Please document the following about this pull request:
### Identify the organization for which you completed this work
If this work is associated with a university course, please identify the university/course/semester (ex. MTU/MIS3200/Fall2023).
* List the organizaiton here: 
* MTU, MIS5000

### Identify what team you are on
* List the team here:
* RA, AppDEV

### Identify the task, story, or GitHub issue associated with this work
* Identify the task/story/issue here:
* Scraping API UI and db Changes
### Identify the particular changes that you made for this pull request
* Describe the changes here: 
* Created Scraping UI and made db table to save scraped data

## Type of Change (check all that apply)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation addition/update (non-breaking change that adds documentation to the system)

## Checklist Before Review
- [x] Do you want to keep your branch for future changes or delete it once it is reviewed?
- [x] I have followed the git practices outlined [here](GitPractices.md) to ensure code conflicts are minimized
- [x] My code follows the style guidelines of this project outlined [here](documentation/StyleGuide.md)
- [x] I have performed a self-review of my code. It runs without errors and follows the [Best Coding Practices](BestCodingPractices.md)
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] There are no API keys, passwords, usernames, or other secrets in the code. I am using .env files for all secrets.
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by jeffreywallphd** [comment]
@Divy0409 please provide testing URLs for HTML, XML, and json files in the description for this pull request. I tried Google and an XML example file. The HTML file saved, the XML file did not. Neither the HTML nor the XML file displayed in the user interface.

**Comment by Divy0409** [comment]
Yes sir that is because of uninstalled libraries.
Try running: pip install -r requirements.txt
And then start server again.

Then here are some examples for scraping:
For XML: https://data.lacity.org/api/views/mkf9-fagf/rows.xml?accessType=DOWNLOAD
For JSON: https://data.lacity.org/api/views/mkf9-fagf/rows.json?accessType=DOWNLOAD
For HTML: https://opendata.dc.gov/datasets/DCGIS::affordable-housing/about
or alternatively you can also use google.com

It is working fine for me please let me what errors you are getting.
image
image
image
image

**Comment by jeffreywallphd** [comment]
@Divy0409 I ran the pip install again, but everything was already satisfied. After restarting the server, that didn't change the results. See the image below. What new libraries did you install recently? The django server doesn't register any errors in command prompt. Is there a django error log? If so, where are the log files?

image

**Comment by jeffreywallphd** [comment]
@Divy0409 I had a conflict with the requirements.txt on my machine when I had fixed one of the install errors earlier. I reset my local repository and was able to get everything working. 

The XML output doesn't show the XML tags. The same is shown in your screenshots. You will likely need to implement something like you did for the HTML so that the browser doesn't hide the tags. Otherwise, it looks great!

**Comment by Divy0409** [comment]
Yes it happened right after i solved html issue and I was unaware of it thank you very much for letting me know.
I have resolved it now again pardon me for recent inconveniences.
I believe now it works fine for all formats.
Though I am not a good Frontend developer for sure :))
image
image
image

**Comment by jeffreywallphd** [comment]
@Divy0409 you're doing great with the UI! Keep it up. I just noticed that the .gitignore has a change that includes .csv, .xml, and .json files. Although we want to keep the scraped data off of GitHub, we may still want to allow for these file types. One way we can get around this is to create a folder in the django backend where the files will be stored. We can then add that entire folder to the .gitignore instead of the file types.

**Comment by Divy0409** [comment]
ok i believe we don't need that folder right now as we are saving data on db but I will create one for future use and I will remove those extensions from .gitignore.

**Comment by Divy0409** [comment]
I have removed those extensions from .gitignore and have created a new folder to save data locally if someone wishes to do so in the future.
That folder is in .gitignore.
Though right now we are saving data directly on the server.
Thank you.

**Review by jeffreywallphd — APPROVED** [review]
Everything looks good. Nice work!

**Pull request merged**
