### PR TITLE
User Profile Integration

### PR DESCRIPTION
**Pull request by Prateeek73**
## Using this Pull Request Template
1. In the Description of Changes section below, please fill out the details requested
2. Create the pull request
3. Check the boxes in the Type of Change section that apply to your changes
4. Check the boxes in the Checklist Before Review section that apply
5. Assign at least two reviewers to review your pull request by clicking the settings icon next to Reviewers

## Description of Changes
Added Profile Section with integratedNode backend for API calls to MYSQL local database
Features added
- Sign up
- Log in
- Reset Password
- Profile page
- Logout

Please document the following about this pull request:
### Identify the organization for which you completed this work
If this work is associated with a university course, please identify the university/course/semester (ex. MTU/MIS3200/Fall2023).
* List the organizaiton here: BA5200 Fall 2024

### Identify what team you are on
* List the team here: Team 4

### Identify the task, story, or GitHub issue associated with this work
* Identify the task/story/issue here: User profile module for end used to register and log into the app

### Identify the particular changes that you made for this pull request
* Describe the changes here: Added Profile Section

## Type of Change (check all that apply)
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x ] Documentation addition/update (non-breaking change that adds documentation to the system)

## Checklist Before Review
- [ x ] Do you want to keep your branch for future changes or delete it once it is reviewed?
- [ x ] I have followed the git practices outlined [here](GitPractices.md) to ensure code conflicts are minimized
- [ x ] My code follows the style guidelines of this project outlined [here](documentation/StyleGuide.md)
- [ x ] I have performed a self-review of my code. It runs without errors and follows the [Best Coding Practices](BestCodingPractices.md)
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] There are no API keys, passwords, usernames, or other secrets in the code. I am using .env files for all secrets.
- [ x ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by yaman-aljnadi** [comment]
I've reviewed the merged files, and it seems there is an issue with the merge. When launching the application, an error message appears, indicating that some files are missing. Could you please investigate and resolve this, then attempt the merge again?

Screenshot 2024-11-15 042012

**Review by yaman-aljnadi — CHANGES_REQUESTED** [review]
I've reviewed the merged files, and it seems there is an issue with the merge. When launching the application, an error message appears, indicating that some files are missing. Could you please investigate and resolve this, then attempt the merge again?

Screenshot 2024-11-15 042012

**Comment by Prateeek73** [comment]
Have added the commit to add that file. The app is running fine now on my system. Do review it once more

**Comment by yaman-aljnadi** [comment]
I have looked over the code and updates, there are some parts that needs to be worked on, and some glitches that needs to be fixed. 

We can discuss them tomorrow in class

**Comment by Prateeek73** [comment]
There is a global delay mechanism in app for consecutive API calls. Hence API calls for sign up and login take time too. 
Just wait for 5-10s before sending any more HTTP request immediately after signining up or after login

**Pull request closed without merging**
