### PR TITLE
Updated 2 files: NewsPage.jsx and NewsListing.jsx; added file: NewsLi…

### PR DESCRIPTION
**Pull request by sdarteh**
NewsListing renders the data output file (.json) into appropriate frontend via the Electron UI.

### CODE REVIEW

**Review by Divy0409 — APPROVED** [review]
Your code is working fine as it should be.
Great addition.
However, it would be great if you add back option in future as once you click on one news you are not able to be back on actual news page .
Thank you.

**Comment by Divy0409** [comment]
Moreover, I am not able to see Pull Request form on your Pull Request. Weird!

**Comment by sdarteh** [comment]
Not your fault bro. Think after realizing I checked two reviewers instead one, I cancelled yours.
Hope all good at your end too. Thanks all same


Sam


Sent from Yahoo Mail for iPhone


On Friday, May 3, 2024, 1:03 AM, Divy Patel ***@***.***> wrote:




Moreover, I am not able to see Pull Request form on your Pull Request. Weird!

**Comment by Divy0409** [comment]
Still when you create a pull request there has to be  a form that you may
need to fill up..

**Comment by Divy0409** [comment]
I was mentioning about that form.
No worries.

**Comment by sdarteh** [comment]
Thank you Divy. Please are you referring to the template of description or a different form entirely?

Thanks 


Sent from Yahoo Mail for iPhone


On Friday, May 3, 2024, 1:30 AM, Divy Patel ***@***.***> wrote:



I was mentioning about that form.
No worries.

**Comment by jeffreywallphd** [comment]
Thanks for getting the news page working!

**Pull request merged**
