### PR TITLE
Mis4000 database

### PR DESCRIPTION
**Pull request by Zdchaudi2829**
## Using this Pull Request Template
1. In the Description of Changes section below, please fill out the details requested
2. Create the pull request
3. Check the boxes in the Type of Change section that apply to your changes
4. Check the boxes in the Checklist Before Review section that apply
5. Assign at least two reviewers to review your pull request by clicking the settings icon next to Reviewers

## Description of Changes
Please document the following about this pull request:
### Identify the organization for which you completed this work
If this work is associated with a university course, please identify the university/course/semester (ex. MTU/MIS3200/Fall2023).
* List the organizaiton here: MIS4000 Fall 2024

### Identify what team you are on
* List the team here: Team 2 - Database

### Identify the task, story, or GitHub issue associated with this work
* Identify the task/story/issue here: Database for Chatbot Training

### Identify the particular changes that you made for this pull request
* Describe the changes here: Creation of Database and addition of Tables

## Type of Change (check all that apply)
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] Documentation addition/update (non-breaking change that adds documentation to the system)

## Checklist Before Review
- [x ] Do you want to keep your branch for future changes or delete it once it is reviewed?
- [ x] I have followed the git practices outlined [here](GitPractices.md) to ensure code conflicts are minimized
- [x ] My code follows the style guidelines of this project outlined [here](documentation/StyleGuide.md)
- [ x] I have performed a self-review of my code. It runs without errors and follows the [Best Coding Practices](BestCodingPractices.md)
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] There are no API keys, passwords, usernames, or other secrets in the code. I am using .env files for all secrets.
- [x ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by vroenVen** [comment]
Test was successful I was able to run the django server on my device. The code looks good and we wont be able to know if there are bugs until we use it to input data.

**Review by sofa23 — APPROVED** [review]
I double checked that the branches being committed to were correct.

**Review by vroenVen — APPROVED** [review]

**Review by Divy0409 — CHANGES_REQUESTED** [review]
You haven't created tables in the database yet because you haven't run python manage.py makemigrations and python manage.py migrate commands.

Which I tried to run and it returned error in sites.py and admin.py which you will need to solve before merging this code into dev branch.

Will help you on Wednesday to understand error and resolve it till then you can try to solve it by yourself.

Thank you.

**Comment by Zdchaudi2829** [comment]
DB Changes and worked with divy to fix errors. Database is now up and working

**Pull request merged**
