### PR TITLE
Create GITUSAGE.md

### PR DESCRIPTION
**Pull request by cletuzz00**
Git usage file with steps on how to install and use github for all teams

## Using this Pull Request Template
1. In the Description of Changes section below, please fill out the details requested
2. Create the pull request
3. Check the boxes in the Type of Change section that apply to your changes
4. Check the boxes in the Checklist Before Review section that apply
5. Assign at least two reviewers to review your pull request by clicking the settings icon next to Reviewers

## Description of Changes
Please document the following about this pull request:
### Identify the organization for which you completed this work
If this work is associated with a university course, please identify the university/course/semester (ex. MTU/MIS3200/Fall2023).
* List the organizaiton here: 

### Identify what team you are on
* List the team here:

### Identify the task, story, or GitHub issue associated with this work
* Identify the task/story/issue here:

### Identify the particular changes that you made for this pull request
* Describe the changes here: 

## Type of Change (check all that apply)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation addition/update (non-breaking change that adds documentation to the system)

## Checklist Before Review
- [x] Do you want to keep your branch for future changes or delete it once it is reviewed?
- [ ] I have followed the git practices outlined [here](GitPractices.md) to ensure code conflicts are minimized
- [ ] My code follows the style guidelines of this project outlined [here](documentation/StyleGuide.md)
- [x] I have performed a self-review of my code. It runs without errors and follows the [Best Coding Practices](BestCodingPractices.md)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] There are no API keys, passwords, usernames, or other secrets in the code. I am using .env files for all secrets.
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by cletuzz00** [comment]
I have added section on how people can use private emails to push changes

**Comment by jeffreywallphd** [comment]
@cletuzz00 thanks for filling out the form, adding the requested info, and assigning reviewers. @yaman-aljnadi please don't feel that you have to do all of the reviews. Use your core team to assist you. This would be a good change to merge directly to main when you feel it is ready. Documentation can be helpful to get on the main branch sooner.

**Comment by yaman-aljnadi** [comment]
Thank you @cletuzz00  for putting together the guide on using Git. I really appreciate the effort you’ve put into it. I may add a few more details to it and plan to incorporate it into the main README.md file soon.

@jeffreywallphd, I will also do my best to get the IT team as involved as possible as the course progress.

**Review by yaman-aljnadi — APPROVED** [review]

**Comment by yaman-aljnadi** [comment]
Also, for the future I wouldn't advice making the changes directly to the main, we have to stay consistent with the Dev branch, since the main is not up-to date with the Dev branch yet

**Pull request merged**
